import "./vendor/jquery.min";
import "./vendor/1.6.3/angular.min";
import "./vendor/1.6.3/angular-route.min";
import "./vendor/toastr.min";
import "./toastr/toastr";
import "./app";
import "./routes";
import "./admin/adminLogin";
// import "./admin/results";
import "./admin/createUsers";
import "./admin/userList";
import "./admin/userDetails";
// import "./app/nav/nav";
import "./security/logout";
import "./security/login";
import "./security/auth";
import "./security/currentIdentity";
import "./security/users";
// import "./app/home/home";
import "./home/createNewSession";
// import "./sessions/sessions";
import "./sessions/unreviewedSessionCount";
// import "./app/sessions/sessionDetail";
// import "./app/sessions/sessionDetailWithVotes";
// import "./app/common/detailPanel";
import "./components/talkDuration";
import "./components/zoomIn";
// import "./app/profile/profile";